name: inventario_merca_inc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  flutter_vector_icons: ^2.0.0
  remixicon: ^1.3.0
  pdf: ^3.10.0
  printing: ^5.11.0
  universal_html: ^2.2.0
  intl: ^0.18.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  firebase_storage: ^12.4.3
  image_picker_web: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/Silla_Inicio.jpg
    - lib/images/Fondo_Reporte.jpg
    - lib/images/FondoLogin.jpg
    - lib/images/Hoja_Membretada.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
