// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwP-bFqvJty3XEgVPsChdb3DDdwYe-GLI',
    appId: '1:653345431959:web:53726e2a59f8ca343864d2',
    messagingSenderId: '653345431959',
    projectId: 'inventario-merca-inc',
    authDomain: 'inventario-merca-inc.firebaseapp.com',
    storageBucket: 'inventario-merca-inc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xT-p_38qMVOdLkQk-Kvps3VyvhQPGVI',
    appId: '1:653345431959:android:eb9776904125f8883864d2',
    messagingSenderId: '653345431959',
    projectId: 'inventario-merca-inc',
    storageBucket: 'inventario-merca-inc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfD0PwQ9A5Yo9WTX8SUdQyK0M8vTzgwuw',
    appId: '1:653345431959:ios:5c55daff3f00dcdc3864d2',
    messagingSenderId: '653345431959',
    projectId: 'inventario-merca-inc',
    storageBucket: 'inventario-merca-inc.firebasestorage.app',
    iosBundleId: 'com.example.inventarioMercaInc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfD0PwQ9A5Yo9WTX8SUdQyK0M8vTzgwuw',
    appId: '1:653345431959:ios:5c55daff3f00dcdc3864d2',
    messagingSenderId: '653345431959',
    projectId: 'inventario-merca-inc',
    storageBucket: 'inventario-merca-inc.firebasestorage.app',
    iosBundleId: 'com.example.inventarioMercaInc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwP-bFqvJty3XEgVPsChdb3DDdwYe-GLI',
    appId: '1:653345431959:web:44b6b0487814d5173864d2',
    messagingSenderId: '653345431959',
    projectId: 'inventario-merca-inc',
    authDomain: 'inventario-merca-inc.firebaseapp.com',
    storageBucket: 'inventario-merca-inc.firebasestorage.app',
  );
}
